#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/hygiene_smoke.sh <scenario> [--keep-open]

Scenarios:
  forbidden-file   Add system_prompt.txt (critical forbidden file)
  professionalism  Add docs file with unprofessional/profane tone
  dual-signal      Add docs file with artifact wording + hostile tone

Options:
  --keep-open      Keep validation PR and branch open after run
EOF
}

if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

SCENARIO="$1"
KEEP_OPEN="false"
if [[ "${2:-}" == "--keep-open" ]]; then
  KEEP_OPEN="true"
fi

if [[ "$SCENARIO" != "forbidden-file" && "$SCENARIO" != "professionalism" && "$SCENARIO" != "dual-signal" ]]; then
  echo "Unknown scenario: $SCENARIO"
  usage
  exit 1
fi

for cmd in git gh; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Missing required command: $cmd"
    exit 1
  fi
done

if [[ -n "$(git status --porcelain)" ]]; then
  echo "Working tree must be clean before running smoke script."
  exit 1
fi

timestamp="$(date +%Y%m%d%H%M%S)"
branch="codex/hygiene-smoke-${SCENARIO}-${timestamp}"

git checkout main >/dev/null
git pull --ff-only origin main >/dev/null
git checkout -b "$branch" >/dev/null

case "$SCENARIO" in
  forbidden-file)
    target="system_prompt.txt"
    cat > "$target" <<'EOF'
INTENTIONAL ADVERSARIAL SMOKE TEST
This file is intentionally forbidden by policy.
EOF
    commit_msg="test(hygiene): smoke forbidden-file"
    pr_title="test(hygiene): smoke forbidden-file"
    ;;
  professionalism)
    target="docs/hygiene-smoke-professionalism.md"
    mkdir -p docs
    cat > "$target" <<'EOF'
# Hygiene Professionalism Smoke

This document is intentionally unprofessional for validation.

This workflow is bullshit and the docs are garbage.
EOF
    commit_msg="test(hygiene): smoke professionalism"
    pr_title="test(hygiene): smoke professionalism"
    ;;
  dual-signal)
    target="docs/hygiene-smoke-dual-signal.md"
    mkdir -p docs
    cat > "$target" <<'EOF'
# Hygiene Dual-Signal Smoke

This file is a temporary validation artifact.

The previous implementation was sloppy and reflects poor engineering judgment.
Any serious engineer would avoid these avoidable mistakes.
EOF
    commit_msg="test(hygiene): smoke dual-signal"
    pr_title="test(hygiene): smoke dual-signal"
    ;;
esac

git add "$target"
git commit -m "$commit_msg" >/dev/null
git push -u origin "$branch" >/dev/null

pr_body="$(cat <<EOF
## Purpose
Validation smoke test for scenario: \`$SCENARIO\`.

## Expected
- Repo Hygiene Review should fail for this adversarial case.
- PR should remain non-mergeable while failed check is present.

## Notes
Generated by \`scripts/hygiene_smoke.sh\`.
EOF
)"

pr_url="$(gh pr create --base main --head "$branch" --title "$pr_title" --body "$pr_body")"
pr_number="$(gh pr view "$pr_url" --json number --jq '.number')"
echo "Opened PR: $pr_url"

echo "Waiting for Repo Hygiene Review run..."
run_id=""
for _ in {1..60}; do
  run_id="$(gh run list --workflow "Repo Hygiene Review" --branch "$branch" --limit 1 --json databaseId --jq '.[0].databaseId // empty')"
  if [[ -n "$run_id" ]]; then
    break
  fi
  sleep 5
done

if [[ -z "$run_id" ]]; then
  echo "Could not find Repo Hygiene Review run for branch $branch"
  exit 1
fi

for _ in {1..120}; do
  status="$(gh run view "$run_id" --json status --jq '.status')"
  if [[ "$status" == "completed" ]]; then
    break
  fi
  sleep 5
done

conclusion="$(gh run view "$run_id" --json conclusion --jq '.conclusion')"
echo "Repo Hygiene Review conclusion: $conclusion"

if [[ "$conclusion" == "failure" ]]; then
  echo "PASS: expected failure observed for scenario '$SCENARIO'."
else
  echo "FAIL: expected failure but got '$conclusion' for scenario '$SCENARIO'."
fi

if [[ "$KEEP_OPEN" == "true" ]]; then
  echo "Keeping PR open for manual inspection: $pr_url"
  exit 0
fi

gh pr close "$pr_number" \
  --comment "Automated hygiene smoke complete for scenario '$SCENARIO' (Repo Hygiene Review: $conclusion). Closing validation PR." \
  --delete-branch >/dev/null

git checkout main >/dev/null
git pull --ff-only origin main >/dev/null
git fetch origin --prune >/dev/null
if git show-ref --verify --quiet "refs/heads/$branch"; then
  git branch -D "$branch" >/dev/null || true
fi

echo "Closed PR and cleaned up branch: $branch"
